site_name: ZSonic Documentations
site_description: 致声制造 产品文档

theme:
  name: material
  language: zh
  features:
    - navigation.indexes
    - navigation.tabs
    - search.highlight
  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

nav:
  - Home: index.md
  - ZSonicMat:
    - Introduction: zsonicmat/zsonicmat_index.md
    - Quick Start: zsonicmat/zsonicmat_quickstart.md
  - About: about.md

markdown_extensions:
  - admonition              # 提示框功能
  - pymdownx.details        # 提示框折叠功能
  - pymdownx.superfences    # 提示框中添加代码
  - pymdownx.arithmatex:    # 渲染数学公式
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - meta:
      enabled: true
# extra_javascript:
#   - javascripts/katex.js
#   - https://unpkg.com/katex@0/dist/katex.min.js
#   - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

# extra_css:
#   - https://unpkg.com/katex@0/dist/katex.min.css

# plugins:
#   - search
#   - blog:
#     blog_toc: true
#     archive_date_format: MMMM yyyy
#     categories_allowed:
#       - Holidays
#       - News
#     authors_profiles: true
#     pagination_per_page: 5
#     archive_pagination_per_page: 10
#     categories_pagination_per_page: 10
#     # post_slugify: !!python/object/apply:ext.slugs.slugify
#     #   kwds:
#     #     short: true
#   - meta
#   - tags
  # - rss:
  #     match_path: "blog/posts/.*"
  #     date_from_meta:
  #       as_creation: date.created
  #       as_update: date.updated
